language: node_js

node_js:
  - "10"

branches:
  only:
  - master
  - develop

install:
  - yarn install

script:
  - yarn run bootstrap
  - yarn run lint:ci
  - yarn run test:ci

cache:
  directories:
    - node_modules

git:
  depth: 1
