version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: yarn install

      - run:
          name: bootstrap
          command: yarn run bootstrap

      - run:
          name: lint
          command: yarn run lint:ci

      - run:
          name:  test
          command: yarn run test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock"" }}

